### PR TITLE
create users signin, login, logout views and routes and added login decorators to prot…

### PR DESCRIPTION
**Pull request by Grandkojo**
…ected views.

### CODE REVIEW

**Review by wodoame — COMMENTED** [review]
Well everything's fine except that you don't need to put the decorators on right now.

**Comment by Grandkojo** [comment]
Alright, I'd change that. I'm off my workspace for today. I'd do it tomorrow

**Review by wodoame — COMMENTED** [review]
``` python 
     form = UserAuthenticationForm(data=request.POST)
     if form.is_valid(): 
           username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
```  
See that section of code?
I think I've done something like this before to get the user

```python
    if form.is_valid(): 
        user = form.user() # I'm not exactly sure if it's that method but something similar to get the user
```
It's just a suggestion though. This is also okay.

**Comment by Grandkojo** [comment]
I've commented out the login_required decorators.

**Comment by Grandkojo** [comment]
> ``` python 
>      form = UserAuthenticationForm(data=request.POST)
>      if form.is_valid(): 
>            username = form.cleaned_data.get('username')
>             password = form.cleaned_data.get('password')
>             user = authenticate(request, username=username, password=password)
> ```  
> See that section of code?
> I think I've done something like this before to get the user
> 
> ```python
>     if form.is_valid(): 
>         user = form.user() # I'm not exactly sure if it's that method but something similar to get the user
> ```
> It's just a suggestion though. This is also okay.

>Okay, I've seen that.  I'd try that maybe next time

**Comment by Grandkojo** [comment]
> ``` python 
>      form = UserAuthenticationForm(data=request.POST)
>      if form.is_valid(): 
>            username = form.cleaned_data.get('username')
>             password = form.cleaned_data.get('password')
>             user = authenticate(request, username=username, password=password)
> ```  
> See that section of code?
> I think I've done something like this before to get the user
> 
> ```python
>     if form.is_valid(): 
>         user = form.user() # I'm not exactly sure if it's that method but something similar to get the user
> ```
> It's just a suggestion though. This is also okay.

> Okay, I've seen that.  I'd try that maybe next time

**Pull request merged**
